### PR TITLE
upgrade to assembly script 0.25 and expose rounding types

### LINKED ISSUE #9: `cmp` is used before being assigned assembly script >= 0.25.0
Starting with assembly script 0.25.0, the build fails with the following error:

```
ERROR TS2454: Variable 'cmp' is used before being assigned.
     :
 676 │ qc[qi++] = cmp ? n : ++n;
     │            ~~~
     └─ in ~lib/as-big/assembly/Big.ts(676,24)

ERROR TS2454: Variable 'cmp' is used before being assigned.
     :
 679 │ if (unchecked(r[0]) && cmp) r[rl] = a.length > ai ? unchecked(a[ai]) : 0;
     │                        ~~~
     └─ in ~lib/as-big/assembly/Big.ts(679,36)

FAILURE 2 compile error(s)
```

It builds correctly with assembly script 0.24.0.

### PR DESCRIPTION
**Pull request by ffortier**
Fixes https://github.com/ttulka/as-big/issues/9

The build is failing with assembly script >0.25.0 because the compiler fails to detect that `cmp` is always set in the for loop. By initializing the variable to 0, we have the same behaviour and the compiler is happy.

I also removed in unused variable `bt` in the same function and exposed constants for the rounding types.

### CODE REVIEW

**Comment by ttulka** [comment]
Thanks for your contribution!
