### ISSUE TITLE
`cmp` is used before being assigned assembly script >= 0.25.0

### ISSUE THREAD

**Issue by ffortier** [ttulka/as-big#9]
Starting with assembly script 0.25.0, the build fails with the following error:

```
ERROR TS2454: Variable 'cmp' is used before being assigned.
     :
 676 │ qc[qi++] = cmp ? n : ++n;
     │            ~~~
     └─ in ~lib/as-big/assembly/Big.ts(676,24)

ERROR TS2454: Variable 'cmp' is used before being assigned.
     :
 679 │ if (unchecked(r[0]) && cmp) r[rl] = a.length > ai ? unchecked(a[ai]) : 0;
     │                        ~~~
     └─ in ~lib/as-big/assembly/Big.ts(679,36)

FAILURE 2 compile error(s)
```

It builds correctly with assembly script 0.24.0.
